### ISSUE TITLE
updating toons

### ISSUE THREAD

**Issue by ryleelewis** [GoldenGnu/jeveassets#117]
every time the program has an update i see errors when i update inventory. today i tried to edit the characters. it worked for one account. when i started a second account nothing happened when i clicked cancel 
![jeveassets_toon_edit_error](https://user-images.githubusercontent.com/32094893/58830247-ea03d400-8617-11e9-8514-c1fefd3eeaee.png)
![account_errors_after_updating](https://user-images.githubusercontent.com/32094893/58830262-ef611e80-8617-11e9-9e97-c8c0a947f3cd.png)
![data_errors](https://user-images.githubusercontent.com/32094893/58830266-f12ae200-8617-11e9-8a1a-97fdfe39a1a7.png)

**Comment by ryleelewis** [comment]
i don't understand why characters would have errors when the 'scopes' never change

**Comment by GoldenGnu** [comment]
The scopes jEveAssets uses may have changed since you added the accounts. Sometimes I add new features that use new endpoints in ESI, and then you have to edit the accounts to add the new scopes to allow access to the new endpoints. That is why it shows the warnings, to let you know it’s not able to get everything. Feel free to just ignore them if you do not want to use the new features.

The problem with not being able to cancel is a CCP problem. The only workaround I can come up with is logout on eveonline.com in your browser, before, adding the next account.

**Comment by ryleelewis** [comment]
Thank you

**Comment by GoldenGnu** [comment]
I'm going to close this issue as resolved. Please, reply if you do not feel it have been resolved and I will reopen the issue
