### ISSUE TITLE
Create an API accessible through excel

### ISSUE THREAD

**Issue by charliedimaggio** [GoldenGnu/jeveassets#118]
As discussed on discord, ever since CCP shutdown the XML API service it has become very difficult to access much of the data that was available via that API natively through excel. There are third party services, but they are usually more catered to market related things. Much of this data exists in jeveassets. It is, for the most part, possible to manually import this data via exporting, but it would be a great enhancement to have the ability to have the data automatically brought into the excel sheet.

Here is an example of an old API key that you could add as a connection in Excel: https://api.eveonline.com/char/WalletTransactions.xml.aspx?keyID=4404311&vCode=DyGe8ub4Wff3QiqOO3kSH05tQ93vaK8Ebg7e92QsSDt8J51mnnKevchjI0OcOZC6&characterID=85021516&rowCount=2560
Which would return something like this: https://i.imgur.com/KSodY9I.png

Thanks as always GoldenGnu.

Charlie

**Comment by deadlybulb** [comment]
Not to distract from jEveAssets (I'm a user) but EveKit (https://evekit.orbital.enterprises) does this depending on the frequency you need (I'm the EveKit developer).  I was generating daily csv dumps for every account but no one was using the feature so I backed it off to weekly.  I can make it daily again if you want to give it a try.  It would dump all of your data in about the same format as the XML api.  What you won't get is the other data jEveAssets downloads and joins, e.g. price data.  Not sure what you're looking for.  I can attach a sample if you want to take a look.

**Comment by charliedimaggio** [comment]
I suspect people don't use csv dumps as it's pretty cumbersome to get data imported into excel on a regular basis. With the connections feature in excel you press one button and it can pull multiple sources of data. Many peoples first steps into coding in Brave started off by making a fairly simple excel sheet and using the XML API feature to bring in the data. My first spreadsheet pulled my market orders, standings and transaction history. This allowed me to figure out a lot about how my orders were performing, how much I was paying in broker fees and other things. Doing this in excel today is much more difficult. I know for certain that if this feature were to be implemented then the members who guide the newer players in brave will be pointing them to jeveassets as it would tick all the right boxes

**Comment by deadlybulb** [comment]
Ah!  If you're willing to use links (I guess I should have assumed that from your initial post), then you don't need a dump at all.  EveKit access keys are basically a rip off of XML credentials.  I should really write this up for all the Excel users out there.  Anyway, an EveKit call would look something like this (fake key, won't work):

https://evekit-model.orbital.enterprises//api/ws/v1/common/wallet_transaction?accessKey=394493959&accessCred=432A741A2F9060A5F0F96BEAE43B387CD43493B769732B70444AE9DBA14D71E&contid=922337203685477600&reverse=true

and would return a JSON blob that looks like this:

```json
[
  {
    "cid": 125156380,
    "eveKitVersion": 2,
    "lifeStart": 1559998670624,
    "lifeEnd": 9223372036854776000,
    "division": 7,
    "transactionID": 5127892690,
    "date": 1559997977000,
    "quantity": 528,
    "typeID": 48112,
    "price": 79711.01,
    "clientID": 2112977716,
    "locationID": 60008494,
    "journalTransactionID": 16851374132,
    "buy": false,
    "personal": false,
    "lifeStartDate": "2019-06-08T12:57:50.624Z",
    "lifeEndDate": "9999-01-01T05:00:00.000Z",
    "dateDate": "2019-06-08T12:46:17.000Z",
    "accountKey": 1006,
    "stationID": 60008494,
    "transactionType": "sell",
    "transactionFor": "corporation"
  },
...
]
```

At least one person is doing this using Google Sheets instead of Excel, but it's the same idea.

EveKit's big win is that it synchronizes all your data for you, so you never miss an update, and it keeps all your history forever.  The tradeoff is that EveKit keeps all your data in the cloud, which some people aren't comfortable with.

Anyway, I'm sure GG will get to your feature eventually.  I can see how people would want to export some data for use in other tools.  EveKit might tie you over until the feature is available.
