### ISSUE TITLE
jEVEasstest failing to load on W10 14931

### ISSUE THREAD

**Issue by MaxRink** [GoldenGnu/jeveassets#2]
Newest Java-version

[hs_err_pid4276.txt](https://github.com/GoldenGnu/jeveassets/files/490752/hs_err_pid4276.txt)
[hs_err_pid17224.txt](https://github.com/GoldenGnu/jeveassets/files/490753/hs_err_pid17224.txt)
[hs_err_pid13156.txt](https://github.com/GoldenGnu/jeveassets/files/490754/hs_err_pid13156.txt)

**Comment by GoldenGnu** [comment]
Thank you for your bug report.
That is a Java crash, not really a bug in jEveAssets.

Suggestions:
1) jEveAssets can get corrupted doing auto update:
Re-installing Java from http://java.com and re-downloading jEveAssets to eliminate that possibility.

2) Sometimes errors like this is caused by corrupted RAM or HDD:
Run a scandisk (make sure to check for bad sectors) and a RAM check to make sure you're in the clear,

3) As, the header in the error logs says, you can report the bug at:
http://bugreport.java.com/bugreport/crash.jsp
If step 1 and 2 did not resolve the issue, this is the next step.

I hope my replay will help you resolve the issue, if not or you need additional help with any of the steps, just reply here again and I will do my best to help you, if possible.
