### ISSUE TITLE
Ability to remove listed stations in Stockpiles

### ISSUE THREAD

**Issue by RustRaven** [GoldenGnu/jeveassets#210]
When creating/editing a stockpile and adding a station location, the list shows all stations where you currently have OR HAD assets. This list is ever-expanding and stations are never removed from them, even if jEveAssets only detected assets there once and they're gone since.

I assume this is just pulling the results from some ESI request, but it would be very helpful to have a way to manually remove stations from that list. When pulling a request from EVE, manually removed stations will show up but jEveAssets would ignore them if there are still no assets detected there.

I hope this makes sense.

**Comment by GoldenGnu** [comment]
It looks like it include all assets, industry jobs, and market orders.
However, since market orders have history, it will include everywhere you ever had orders.
I feel like that is not really something anyone wants, so, I think the proper fix is to only include active orders.
Would you agree with that? or do you still want the solution you suggested?

**Comment by RustRaven** [comment]
I think that would be perfectly fine! I only suggested adding it as an extra option in case there was people who would somehow find that useful (I don't see why but that's just me).

**Comment by GoldenGnu** [comment]
Released in 6.7.0
