### ISSUE TITLE
System name, constellation name and region name columns on the industry window.

### ISSUE THREAD

**Issue by shutupandshave** [GoldenGnu/jeveassets#237]
Could I please have system name, constellation name and region name columns on the industry window.  It will allow me to guess which characters  I can build with.
Fleshing it out a little bit, it would be nice to set a home system and have an additional column that lets you know how far you are from it... 
i.e. char 1 is in the home system, char 2 is 20 jumps from it but has skills to build and research so it can still do that.  Char 3 is 26 jumps from the home system so shows in red in that column because he cant do any actions.

**Comment by GoldenGnu** [comment]
Constellation data is not yet available (it's in the works:  https://github.com/GoldenGnu/jeveassets/issues/229).
Station/System/Region are available.
Additionally, it have been requested the active ship is added as well (by MaddMaxx2000)

How important is it to have the system in a separate column? The system name is always part of the station name.

It may be useful to have the data in both the Industry Slots and the Isk tool

**Comment by crmason2** [comment]
Also the home system you set in game does not appear to be available in ESI anywhere that I can tell @GoldenGnu correct me if I'm wrong on that one.

I've got it location working in a branch with it on the Industry Slots tab, might be fairly simple to get it on the Isk tool as well if we want it in on both. Adding the ship type should be fairly simple since that's on the object I'm using already but I'm not sure if ship name is included if that's important.

**Comment by GoldenGnu** [comment]
There is already a system for adding new columns with jump count from X to Y system:
See `net.nikr.eve.jeveasset.gui.shared.menuJMenuJumps`
I would much rather use that system, so, people can set any system, instead of it only be limited to the home system.
If it's is in ESI, it gotta be on the character sheet, would be my guess. But, I don't know

Ship typeID and name and char location are being updated in: `net.nikr.eve.jeveasset.io.esi.EsiShipGetter`
I think, it would be best to just add those values to OwnerType > AbstractOwner
So, they are easily accessible.

**Comment by GoldenGnu** [comment]
Released in 6.8.0
