### ISSUE TITLE
Why is jEveAssets reading my local data?

### ISSUE THREAD

**Issue by lord-carlos** [GoldenGnu/jeveassets#24]
Jeveassets just died on me: https://eve.nikr.net/jeveassets/bugs/?#bugid616
`Malformed input or input contains unmappable characters: /home/carlos/Klei unter den F����en.mp4`

For what does it need to know what files I have in /home?

Is there a way I can see the full stacktrace? I would love to see which heveassts method caused this.

**Comment by GoldenGnu** [comment]
1) Thank you for your bug report and thank you for creating a GitHub issue too.
It helps a lot to be able to talk with the users, who found the bug.

2) I not sure what it was doing in that folder, maybe it was creating JFileChooser for the user directory, but, it's just a guess.

3) That is the full stack trace, it's not a jEveAssets bug, it's a java bug. It's most likely related to [JDK-8003228](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8003228). There is a question on Stack Overflow too: [InvalidPathException for chinese filename](https://stackoverflow.com/questions/37409379/invalidpathexception-for-chinese-filename)

I will need a few things to debug this:
- Please email me the log (See the [Wiki](https://github.com/GoldenGnu/jeveassets/wiki/ReadMe#bugs) for steps).
- I need to know your Java version and if you have OpenJDK or Oracle Java installed
- If you're able to reproduce the bug, could you try running jEveAssets with the following:
`java -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 -jar jeveassets.jar`
That should force Java to use UTF-8 encoding and should stop Java from crashing with this error.

**Comment by lord-carlos** [comment]
3. Well the last line is ` at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run(BasicDirectoryModel.java:228)` should a full stack trace not tell me what code in jEveAssets called this method?

Anyhow, when I get home I will check for the data you asked for. Poke me again in a few days, because I might forget.

**Comment by GoldenGnu** [comment]
Java stack traces doesn’t always work like that, because, a lot of the GUI code is part of Java. Swing sometimes throws errors, that is not the result of a jEveAsset call, but, a result of the user interacting with the GUI.

**Comment by lord-carlos** [comment]
* I'm running OpenJDK
```
java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```
* Your bug database says I'm using Oracle Java. Is there a bug in your bug database? :D

* Using the UTF-8 parameters fixes the problem. :+1: 

* Do you stil need the full log? The error always occurs right after `INFO: [AWT-EventQueue-1] net.nikr.eve.jeveasset.Program - Loading: Assets Tab` I don't know how threaded the application is at that point.

I still feel uneasy about it reading my data. Because, you know, around here we don't trust people from Sjælland.

**Comment by GoldenGnu** [comment]
- OpenJDK identifies as Oracle Java, because: **Java Logic™**

- Thank you for testing the fix. I have to look into a more permanent solution, but, I hope to have this fixed in the next release.

- The issue of trust:
I'm going to walk you though the source...
[Program](https://github.com/GoldenGnu/jeveassets/blob/master/src/main/java/net/nikr/eve/jeveasset/Program.java#L206) ->[AssetTab](https://github.com/GoldenGnu/jeveassets/blob/master/src/main/java/net/nikr/eve/jeveasset/gui/tabs/assets/AssetsTab.java#L125) > [AssetTab.AssetFilterControl ](https://github.com/GoldenGnu/jeveassets/blob/master/src/main/java/net/nikr/eve/jeveasset/gui/tabs/assets/AssetsTab.java#L273) -> [FilterControl](https://github.com/GoldenGnu/jeveassets/blob/master/src/main/java/net/nikr/eve/jeveasset/gui/shared/filter/FilterControl.java#L108) -> [FilterGui](https://github.com/GoldenGnu/jeveassets/blob/master/src/main/java/net/nikr/eve/jeveasset/gui/shared/filter/FilterGui.java#L85) ->[ExportDialog](https://github.com/GoldenGnu/jeveassets/blob/master/src/main/java/net/nikr/eve/jeveasset/gui/shared/filter/ExportDialog.java#L159) -> [JCustomFileChooser](https://github.com/GoldenGnu/jeveassets/blob/master/src/main/java/net/nikr/eve/jeveasset/gui/shared/components/JCustomFileChooser.java#L38)
The default directory for the JFileChooser is the users home directory

You can test this is true, by:
1) Go to the Assets Tool
2) Click `Export`
3) Press `Default`
4) Press `OK`
The `JFileChooser` should now open in your home directory

> don't trust people from Sjælland.

That is fair and but, you don't have to rely on trust, It would be much better if you did a full code review of the entire code base of jEveAssets, before you use it again IMHO. Please, create issues for any bug you find along the way, thanks :D

**Comment by GoldenGnu** [comment]
https://github.com/GoldenGnu/jeveassets/releases/tag/jeveassets-5.1.1 have been released, if you could verify that it works without the command line parameters, that would be great.

I'm going to close this issue, but, please, reply here when you have tested the latest version, thanks.

**Comment by lord-carlos** [comment]
It's gucci now!
Works fine. Thanks for the quick fix.

**Comment by GoldenGnu** [comment]
Thank you for verifying the fix :)
