### ISSUE TITLE
Reprocessed Value is not station relevant

### ISSUE THREAD

**Issue by zinsmeik** [GoldenGnu/jeveassets#312]
Hi,
I think the calculation of the "Price if asset was reprocessed" in column "Reprocessed"  is wrong. 
The reprocessing value does not depend on the Station (except for ore). 
In the Settings you can set a "Station Refining Equipment" of 50% or a custom value. However this value has only impact on reprocessing ore. 
For reprocessing of an item like Metal Scraps only the Scrapmetal Processing Skill is relevant. But when I change the "Station Refining Equipment"   the value for the reprocessing column change.

Greetings

Klaus

**Comment by GoldenGnu** [comment]
Good catch! 👍
I'm going to fix that.

I'm also going to add a setting for ore processing skill (just one covering all of them, not all the ore specific skills).
So you can set the ore processing and scrapmetal processing independently. It makes more sens to me, since the two processes have no connection.

**Comment by GoldenGnu** [comment]
Released in 7.2.0
