### ISSUE TITLE
Stockpile Subpile Total

### ISSUE THREAD

**Issue by Mr00Anderson** [GoldenGnu/jeveassets#386]
When having subpiles it would be nice to see the cost of that subpile on the stockpile that its for based on the quantity for that sockpile.  See picture for example.

![image](https://user-images.githubusercontent.com/1356935/235248700-ab8f1b6b-33f4-478e-b2b2-21a31110dcd4.png)

**Comment by GoldenGnu** [comment]
I think that would be hard to add, since the individual subpiles are basically ignored and only the total for each item (from all subpiles and the stockpile itself) are calculated. I'm not even sure how to calculate it, as you could have a situation with two subpiles having the same item and not enough stock for both of them, meaning you would have to somehow split the stock between them. I think this adds too much complexity, to justifying doing it.
