### ISSUE TITLE
market orders » regional buy orders

### ISSUE THREAD

**Issue by Joel861** [GoldenGnu/jeveassets#417]
make it possible that the programs recognizes regional BUY orders que. this way it wouldnt flash as red if my order was the first regional order but at a lower price on the que. it would save a lot of time for everyone

**Comment by GoldenGnu** [comment]
I'm not 100% sure what you want to change, sorry-

The way that buy orders outbid work is as follow:
If your buy order is set to region it's compared to all orders in the region.
If it have any other range, it will take the range of you order: X and the range of every other order: Y, then will add those see if that is less than the number of jumps between the orders: X + Y < Jumps. If that is case, it will be compared. otherwise it will be ignored. So, in short: It will compare every order that overlap your order range.

It's already possible to set the range of sell order (they're always region range), but, it still make sense to compare then at other ranges too. This would be possible for buy orders too. Atm. It simply use the buy orders range.

**Comment by GoldenGnu** [comment]
I'm going to close this as resolved, as the user never replayed to the follow up question
