### ISSUE TITLE
Feature Request: Add a setting to update ESI data every X number of hours while the program is open.

### ISSUE THREAD

**Issue by Peanut3351** [GoldenGnu/jeveassets#437]
There is currently an option to run the program from task scheduler to do background updates, but it would be nice if we could set a simple option in the settings to refresh at a given interval when the program is open.

**Comment by GoldenGnu** [comment]
The problem with updating in the background is that jEveAssets need to lock the GUI while it updates the data in the tools. If the update is done in the background there isn’t a good way to handle that. Either you have to still require the user to select when to update the data in tools or you have to just update without the users consent, which means they will be interrupted in whatever they’re doing. On top of that I recently had to remove the automatic public market orders update due to it going haywire and impacting ESI and thereby eve.

I understand why this would be useful, but, for the reasons above, I’m going to reject this feature request.
