### ISSUE TITLE
"Grand Total" Sums should include an option to ignore filtered results

### ISSUE THREAD

**Issue by Groot2C** [GoldenGnu/jeveassets#443]
Feature request: for the "Grand Total" row to have the option to exclude filtered results. For example, on the "Slots" page it sums up all 60 of my characters instead of just the 20 that do Reactions/Manufacturing. Therefore, I have an "extra" 40 Reaction/Manufacturing/Researching slots than I "actually" have. 

This is even after I add a filter "Reactions Max - Does Not Equals 1".

**Comment by GoldenGnu** [comment]
I'm going to reject this feature, for the following reasons:
The total for shown/filtered slots are already shown in the statusbar.
Changing table data on filtering can create a paradoxical state. Since every time you filter on the data, the data change, so you have to filter again, which may change the data again etc. leading to an endless loop. Which means it's very hard to do right. In this case the data is already available, so I don't think it's worth the effort.

If you have a good argument for implementing this regardless of the above, I'm always open to discussing it, either here or on discord. Nothing is set in stone.
